name = "Dreamteam 2026"
author = "Arnau Mora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22700e49edd31faa98a5693d95411b096c47b55f12b876417e1da5accdd178ce"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
