name = "Dreamteam 2026"
author = "Arnau Mora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e475275966accf8e3ec8ee5d65db0af0c6595bb4627bde639f8bf3cad429beec"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
