name = "Dreamteam 2026"
author = "Arnau Mora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0adbbafb39eca8710156a1b3e9733952de7cc1475e5dd9e85e498f82f7a388f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
