name = "Dreamteam 2026"
author = "Arnau Mora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75d23a8b72e5047c5bd24095e89a31a11cea9911d4b6f047d2ce4b8f5b838f9a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
