name = "Dreamteam 2026"
author = "Arnau Mora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4aa3d48e3aa273a338abbab11996c32d0365fcd94e83561cd828b2f7dfa5493c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
