name = "Dreamteam 2026"
author = "Arnau Mora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "517c2f374cd784a5285e9e7459459ad0df4e561efc807610a18a311dca632f3f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
