name = "Dreamteam 2026"
author = "Arnau Mora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6d5a53a0890ed388537d93d43d9c03eae33acde6f2dbf5bdafbff6acc100730"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
