name = "Dreamteam 2026"
author = "Arnau Mora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d65c49b440f6290b46819c0e27fdc2c4623d277342bc370ffde7abbd350288e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
