name = "Dreamteam 2026"
author = "Arnau Mora"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcb1df7128522d3fd19058fb81e3ffc288390d4e007d110c89c4d8aa18196939"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
